### ISSUE TITLE
Role and ClusterRole

### ISSUE THREAD

**Issue by pierrevillard** [reddec/ingress-dashboard#2]
Hi,

I noticed that file : https://github.com/pierreilki/ingress-dashboard/blob/master/ingress-dashboard.yaml declare a K8S Role and a ClusterRole, both binded to "ingress-dashboard" ServiceAccount. Does your application really need "ingress-dashboard" Role, and "ingress-dashboard" RoleBinding if a ClusterRole and a ClusterRoleBinding with sames rights are already declared and binded to your SA ?

If no, i can update this file :)

**Comment by reddec** [comment]
CR and CRB should be enough, thanks!

Unfortunately we have to use Cluster kind of permissions due to watch in all namespaces

**Comment by pierrevillard** [comment]
@reddec OK! :)

I opened a PR. Cluster Kind RBAC is normal for your app i think :)

Have a nice day
